# Default values for coacervate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Local storage if running on e.g. minikube
local:
  enabled: true
  storageClass: manual
  pvPath: "" # existing path on k8s node e.g. /var/lib/yagna
  nodeHostName: "" # k get nodes --show-labels | grep hostname
  pvName: yagna-local-pv
  reclaimPolicy: Retain

# Yagna deployment values
yagna:
  storageClass: ""
  deploymentName: yagna-deployment
  containerName: yagna-deployment-container
  imageRepo: coacervate/yagna
  imageTag: latest
  imagePullPolicy: Always
  pvcName: yagna-pvc
  rootVolName: yagna-storage
  socketSubpath: yagna-socket
  socketMount: /yagna # Allows yagna daemon to communicate over unix socket
  gsbEnvKey: GSB_URL # Specifies unix socket location for communicating with daemon
  gsbEnvValue: unix:/yagna/yagna.sock
  keySubpath: yagna-keys
  keyMount: /root/.local/share/yagna # Default location yagna looks for appkeys etc
  svcName: yagna-service
  apiEnvKey: YAGNA_API_URL
  port: 7465

# For importing and existing keystore
# see https://handbook.golem.network/payments/using-golem-on-mainnet/backing-up-your-golem-wallet
existingWallet:
  enabled: false
  keystoreFilePath: files/example_keystore.json
  volName: keystore-volume
  secretName: keystore-secret
  mountPath: /mnt/secrets/yagna_keystore.json
  contentsKey: yagna-keystore
  pathKey: yagna-keystore-path
  networkKey: payment-network
  networkValue: polygon
  driverKey: payment-driver
  driverValue: erc20

# Values for templates/tests
test:
  pvName: test-pv
  pvcLabel: test-storage-label
  pvcName: test-pvc
  podImageRepo: coacervate/test-requestor
  podImageTag: latest