# Default values for coacervate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

manualJob:
  enabled: false
  jobName: call-variants-benchmark
  containerName: requestor
  inputHostPath: ""
  containerMountPath: "/data/results"

# Local storage if running on e.g. minikube
local:
  enabled: false
  storageClass: manual
  pvPath: ""
  nodeHostName: "" # k get nodes --show-labels | grep hostname
  pvName: yagna-local-pv

image:
  yagna:
    repository: coacervate/yagna
    tag: latest
    pullPolicy: Always
  requestor:
    repository: coacervate/requestor
    tag: latest
    pullPolicy: Always

yagna:
  storageClass: local-path # Default minikube storage class, adjust PVC as needed
  deploymentName: yagna-deployment
  pvName: yagna-pv
  pvcName: yagna-pvc
  rootVolName: yagna-storage
  socketSubpath: yagna-socket
  socketMount: /tmp # Allows yagna daemon to communicate over unix socket
  keySubpath: yagna-keys
  keyMount: /root/.local/share/yagna # Default location yagna looks for appkeys etc
  svcName: yagna-service
  port: 7465