# Default values for coacervate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Local storage if running on e.g. minikube
local:
  enabled: false
  storageClass: local-sc
  pvPath: "" # existing path on k8s node e.g. /var/lib/yagna
  nodeHostName: "" # kubectl get nodes --show-labels | grep hostname
  pvName: yagna-local-pv

# Yagna deployment values
yagna:
  storageClass: ""
  deploymentName: yagna-deployment
  containerName: yagna-deployment-container
  imageRepo: coacervate/yagna
  imageTag: latest
  imagePullPolicy: Always
  pvName: yagna-pv
  pvcName: yagna-pvc
  rootVolName: yagna-storage
  socketSubpath: yagna-socket
  socketMount: /tmp # Allows yagna daemon to communicate over unix socket
  keySubpath: yagna-keys
  keyMount: /root/.local/share/yagna # Default location yagna looks for appkeys etc
  svcName: yagna-service
  port: 7465

secret:
  keystoreFilePath: files/example_keystore.json

# Values for templates/tests
test:
  pvName: test-pv
  pvcLabel: test-storage-label
  pvcName: test-pvc
  podImageRepo: coacervate/test-requestor
  podImageTag: latest