apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.yagna.deploymentName }}
  labels:
    {{- include "coacervate.labels" . | nindent 4 }}
    module: yagna-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      {{- include "coacervate.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coacervate.selectorLabels" . | nindent 8 }}

    spec:
      volumes:
        - name: {{ .Values.yagna.rootVolName }}
          persistentVolumeClaim:
            claimName: {{ .Values.yagna.pvcName }}
        - name: {{ .Values.existingWallet.volName }}
          secret:
            secretName: {{ .Values.existingWallet.secretName }}
            optional: true
      containers:
        - name: {{ .Values.yagna.containerName }}
          image: "{{ .Values.yagna.imageRepo }}:{{ .Values.yagna.imageTag }}"
          imagePullPolicy: {{ .Values.yagna.imagePullPolicy }}
          volumeMounts:
            - name: {{ .Values.yagna.rootVolName }}
              mountPath: {{ .Values.yagna.keyMount }}
              subPath: {{ .Values.yagna.keySubpath }}
            - name: {{ .Values.yagna.rootVolName }}
              mountPath: {{ .Values.yagna.socketMount }}
              subPath: {{ .Values.yagna.socketSubpath }}
            - name: {{ .Values.existingWallet.volName }}
              mountPath: {{ .Values.existingWallet.mountPath }}
              subPath: {{ .Values.existingWallet.keyName }}
              readOnly: true
          env:
          - name: YAGNA_API_URL
            value: "http://0.0.0.0:7465"
          - name: KEYSTORE_PATH
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingWallet.secretName }}
                key: {{ .Values.existingWallet.pathKey }}
                optional: true
          command:
            - sleep
            - infinity
          ports:
          - containerPort: {{ .Values.yagna.port }}
