{{ if .Values.existingWallet.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingWallet.secretName }}
type: Opaque
data:
  {{ .Values.existingWallet.contentsKey }}: {{ .Files.Get .Values.existingWallet.keystoreFilePath | b64enc | quote }}
  {{ .Values.existingWallet.pathKey }}: {{ .Values.existingWallet.mountPath | b64enc | quote }}
{{ end }}