{{ if .Values.local.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.local.storageClass }}
  labels:
    {{- include "coacervate.labels" . | nindent 4 }}
    module: yagna
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{ end }}