apiVersion: v1
kind: PodTemplate
metadata:
  name: my-pod-template
template:
  metadata:
    labels:
      module: yagna
  spec:
    volumes:
      - name: {{ .Values.yagna.rootVolName }}
        persistentVolumeClaim:
          claimName: {{ .Values.yagna.pvcName }}
    containers:
      - name: primary
        image: docker.io/rwgrim/docker-noop
        imagePullPolicy: Always
        volumeMounts:
        - name: {{ .Values.yagna.rootVolName }}
          subPath: {{ .Values.yagna.socketSubpath }}
          mountPath: {{ .Values.yagna.socketMount }}
        env:
        - name: YAGNA_API_URL
          value: "http://{{ .Values.yagna.svcName }}:{{ .Values.yagna.port }}"
